frontend:
    build: ./frontend
    expose:
      - 4000
    ports:
      - 4000:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    links:
      - server  